import ReduxProvider from '@/providers/ReduxProvider'
import SessionProvider from '@/providers/SessionProvider'

import {Header} from '@/components'

import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <SessionProvider>
            <Header />
            <div className='container'>
                {children}
              </div>
          </SessionProvider>
        </ReduxProvider>
        </body>
    </html>
  )
}
